program tests

  ! Driver program for FRUIT unit tests in:
  ! calculator_test.f90

  ! Generated by FRUITPy.

  use fruit
  use calculator_test

  implicit none

  call init_fruit

  call run_test_case(test_calculator_should_produce_4_when_2_and_2_are_inputs,"test_calculator_should_produce_4_when_2_and_2_are_inputs")

  call fruit_summary
  call fruit_finalize

end program tests